#include <iostream>
#include <vector>
#include <cmath>
#include <fftw3.h>
#include <fstream>
#include <thread>
#include <arpa/inet.h>
#include <unistd.h>
#include <cstring>
#include <portaudio.h>
#include <chrono>
#include <sstream>

#define SAMPLE_RATE 96000
#define UPSAMPLED_RATE (SAMPLE_RATE)

#define DURATION 5.0
#define F1 20.0
#define F2 20000.0

#define CMD_PORT 1235
#define AUDIO_PORT 1234

#define SAMPLES_PER_PACKET 256
#define BUFFER_SIZE 4096

// =========================
// Simple linear interpolation between measured points
// =========================
double interpLinear(const std::vector<double>& x, const std::vector<double>& y, double xi)
{
    if (x.empty()) return 0.0;

    //Clamp to boundaries
    if (xi <= x.front()) return y.front();
    if (xi >= x.back())  return y.back();

    // find interval 
    int lo = 0;
    int hi = (int)x.size() - 1;
    while (hi - lo > 1) {
        int mid = (lo + hi) / 2;
        if (x[mid] > xi) hi = mid;
        else             lo = mid;
    }

    // Linear interpolation
    double x0 = x[lo];
    double x1 = x[hi];
    double y0 = y[lo];
    double y1 = y[hi];

    double t = (xi - x0) / (x1 - x0);
    return y0 + t * (y1 - y0);
}

// =========================
// Loads a frequency response text file in (format freq spl phase)
// =========================
bool loadFreqResponse(const std::string& filename, std::vector<double>& freq, std::vector<double>& spl)
{
    //Clear outpt vectors
    freq.clear();
    spl.clear();

    //Ooen the file for reading
    std::ifstream in(filename);

    //Error if file cannot be opened 
    if (!in.is_open()) {
        std::cerr << "Failed to open " << filename << "\n";
        return false;
    }

    std::string line;
    //Read the file line by line
    while (std::getline(in, line)) {
        //skip empty lines
        if (line.empty()) continue;
        //convert the line into a stream so numbers can be passed.
        std::istringstream iss(line);
        double f, s, p;
        if (!(iss >> f >> s >> p)) {
            // skip non-numeric lines (headers etc.)
            continue;
        }
        //Parse frequency and SPL
        freq.push_back(f);
        spl.push_back(s);
    }

    // If no valid numeric rows were found, give error
    if (freq.empty()) {
        std::cerr << "No data in " << filename << "\n";
        return false;
    }

    return true;
}

// =========================
// buildCalibrationFile: corr_dB(f) = ref_dB(f) - test_dB(f)
// =========================
bool buildCalibrationFile(const std::string& refFile, const std::string& testFile, const std::string& outFile)
{
    //vectors to hold reference microphone data
    std::vector<double> f_ref, spl_ref;

    //vectors to hold test microphone(Used microphone) data
    std::vector<double> f_test, spl_test;

    //Load reference and test microphone data
    if (!loadFreqResponse(refFile, f_ref, spl_ref)) return false;
    if (!loadFreqResponse(testFile, f_test, spl_test)) return false;

    //Open output file where calibration curve is stored 
    std::ofstream out(outFile);
    if (!out.is_open()) {
        std::cerr << "Failed to open " << outFile << " for writing\n";
        return false;
    }

    // Use reference frequency grid, interpolate test onto it
    for (size_t i = 0; i < f_ref.size(); ++i) {
        double f = f_ref[i];
        double ref_dB  = spl_ref[i];

        // Interpolate test microphone SPL at the same frequency
        double test_dB = interpLinear(f_test, spl_test, f);

        //compute correction data
        double corr_dB = ref_dB - test_dB;

        //Write frequency and the corrected dB to output file
        out << f << " " << corr_dB << "\n";
    }

    //debug write
    std::cout << "Calibration file written to " << outFile << "\n";
    return true;
}

// =========================
// loadCalibration,Loads a calibration file previously generated by buildCalibrationFile
// =========================
bool loadCalibration(const std::string& filename, std::vector<double>& freq, std::vector<double>& corr_dB)
{
    //Clear outpt vectors
    freq.clear();
    corr_dB.clear();


    //Open calibration file
    std::ifstream in(filename);
    if (!in.is_open()) {
        std::cerr << "Failed to open calibration file " << filename << "\n";
        return false;
    }

    std::string line;

    //Read the file line by line
    while (std::getline(in, line)) {
        //skip empty lines
        if (line.empty()) continue;
        //Convert string for numeric parsing
        std::istringstream iss(line);
        // f:frequency, c:correction_dB
        double f, c;
        //Parse numbers from line into variables.
        if (!(iss >> f >> c)) continue;
        //Store passed values
        freq.push_back(f);
        corr_dB.push_back(c);
    }

    //Check if any data was in the file, if not give error.
    if (freq.empty()) {
        std::cerr << "No data in calibration file " << filename << "\n";
        return false;
    }
    return true;
}

// =========================
// sendStart, Sends a small message "START" to the ESP32 to begin audio capture
// =========================
void sendStart()
{
    // Create a UDP socket, AF_INET  = IPv4, SOCK_DGRAM = UDP, 0 = default protocol (UDP)
    int sock = socket(AF_INET, SOCK_DGRAM, 0);

    // Prepare the destination address structure
    sockaddr_in addr{};
    addr.sin_family = AF_INET; //IPv4
    addr.sin_port   = htons(CMD_PORT); //Convert port to network byte order

    // Convert the string "192.168.4.1" into a binary IP address and store it in addr.sin_addr. This is the ESP32's Wi‑Fi AP address
    inet_pton(AF_INET, "192.168.4.1", &addr.sin_addr);

   // The message we want to send.    
    const char* msg = "START";

    // Send the UDP packet.
    // Parameters:
    //   sock           = socket descriptor
    //   msg            = pointer to data
    //   strlen(msg)    = number of bytes to send
    //   0              = no special flags
    //   addr           = destination address
    //   sizeof(addr)   = size of address structure
    sendto(sock, msg, strlen(msg), 0, (sockaddr*)&addr, sizeof(addr));

    // Close the socket
    close(sock);
}


// =========================
// generateSweep, Generates a logarithmic sine sweep using the René Farina exponential formula
// =========================
std::vector<double> generateSweep(double A)
{
    //Total number of samples in the sweep
    int N = SAMPLE_RATE * DURATION;

    //Allocate space in memmory for samples
    std::vector<double> s(N);

    //This calculates the speed of the sweep
    double K = log(F2 / F1);

    for (int n = 0; n < N; n++)
    {
        //Convert sample index to time in seconds
        double t = (double)n / SAMPLE_RATE;
        //Compute phase of the exponential sweep
        double phase = 2 * M_PI * F1 * DURATION / K * (exp(t * K / DURATION) - 1);

        //Generate the sine wave sample at this phase, multiply with "A" for loudness control
        s[n] = A * sin(phase);   // amplitude control here
    }

    return s;
}

// =========================
// AudioData, struct used to pass sweep playback state into the PortAudio callback
// =========================
struct AudioData {
    //Pointer to sweep samples
    const std::vector<double>* sweep;
    //current playback position
    int index = 0;
};

// =========================
// audioCallback, real time audio callback used by PortAudio
// =========================
static int audioCallback(const void*, void* outBuf, unsigned long frames, const PaStreamCallbackTimeInfo*, PaStreamCallbackFlags, void* userData)
{
    //Use the AudioData struct to parse pointers to the sweep
    AudioData* d = (AudioData*)userData;

    //Cast the output due to formatting
    float* out = (float*)outBuf;

    //Loop over the number of frames PortAudio wants to output
    for (unsigned long i = 0; i < frames; i++)
    {
        //If all sweep samples are played return
        if (d->index >= (int)d->sweep->size())
            return paComplete;
        //Write one sample to the output buffer
        *out++ = 0.02f * (*d->sweep)[d->index++];
    }

    return paContinue;
}

// =========================
// playSweep, Plays the generated sweep through the default audio output device using PortAudio
// =========================
void playSweep(const std::vector<double>& sweep)
{
    // Initialize the PortAudio library
    Pa_Initialize();

    //Create an AudioData struct to hold playback state
    AudioData data;
    //pointer to the sweep samples
    data.sweep = &sweep;

    // Pointer to the PortAudio stream object
    PaStream* stream;

    //Open the default audio output stream.
    Pa_OpenDefaultStream(&stream, 0, 1, paFloat32, SAMPLE_RATE, 256, audioCallback, &data);

    // Start the audio stream
    Pa_StartStream(stream);

    //Wait until playback is finished
    while (Pa_IsStreamActive(stream))
        Pa_Sleep(50);

    //Close the audio stream
    Pa_CloseStream(stream);

    //Shut down the PortAudio system
    Pa_Terminate();
}

// =========================
// capture, Receives audio samples streamed over UDP from the ESP32
// =========================
std::vector<double> capture()
{
    // Create a UDP socket, AF_INET  = IPv4, SOCK_DGRAM = UDP, 0 = default protocol (UDP)
    int sockfd = socket(AF_INET, SOCK_DGRAM, 0);

    //Configure the local address to bind to
    sockaddr_in serv{};
    serv.sin_family = AF_INET;          //IPv4
    serv.sin_addr.s_addr = INADDR_ANY;  //Listen on all interfaces
    serv.sin_port = htons(AUDIO_PORT);  //Port ESP32

    // Bind the socket to receive packets
    bind(sockfd, (sockaddr*)&serv, sizeof(serv));

    //1‑second receive timeout so recvfrom() doesn't block forever
    struct timeval tv{1,0};
    setsockopt(sockfd, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(tv));

    // Allocate space for whole recording
    std::vector<double> data;
    data.reserve((size_t)(SAMPLE_RATE * DURATION));

    //Incoming buffer
    char buffer[BUFFER_SIZE];
    //Sender adress (ESP32)
    sockaddr_in cli{};  
    socklen_t len = sizeof(cli);

    //Last recived sequence number
    uint32_t lastSeq = 0;
    //Counter for missing packets
    int lostPackets = 0;

    //Size of sequence number 
    const size_t headerSize = sizeof(uint32_t);

    //Start timing, used to detect when ESP32 Stops sending
    auto start = std::chrono::high_resolution_clock::now();

    //Main recive looå
    while ((int)data.size() < SAMPLE_RATE * DURATION)
    {
        //Recive UDP packet
        int n = recvfrom(sockfd, buffer, BUFFER_SIZE, 0,
                         (sockaddr*)&cli, &len);
        
        //If packet is valid 
        if (n > 0)
        {
            //Check if package is at least size of the sequence number
            if (n < (int)headerSize)
                continue;

            // Extract sequence number from packet header
            uint32_t seq;
            memcpy(&seq, buffer, sizeof(uint32_t));

            //Check if packet was lost
            if (lastSeq != 0 && seq > lastSeq + 1) {
                uint32_t missing = seq - (lastSeq + 1);
                lostPackets += missing;

                // Insert empty values for missing packets
                size_t missingSamples = missing * SAMPLES_PER_PACKET;
                for (size_t i = 0; i < missingSamples; i++)
                    data.push_back(0.0);

                std::cout << "Missing " << missing << " packets\n";
            }

            // Update last received sequence number
            lastSeq = seq;

            // Number of bytes containing audio samples
            int sampleBytes = n - headerSize;

            // Number of int32_t samples in this packet
            int samples = sampleBytes / sizeof(int32_t);

            // Warn if packet size is unexpected
            if (samples != SAMPLES_PER_PACKET) {
                std::cout << "Warning: expected 256 samples, got "
                          << samples << "\n";
            }

            // Pointer to the sample data
            int32_t* ptr = (int32_t*)(buffer + headerSize);

            //Convert each sample from int32_t to doubles
            for (int i = 0; i < samples; i++)
            {
                // normalize 32‑bit PCM to [-1, 1]
                double s = (double)ptr[i] / 2147483648.0;

                // Apply gain (20x)
                s *= 20.0;

                // Clip to [-1, 1] to avoid overflow
                if (s > 1.0) s = 1.0;
                if (s < -1.0) s = -1.0;

                // Store sample
                data.push_back(s);
            }
        }

        //Timeout check
        auto now = std::chrono::high_resolution_clock::now();
        double elapsed = std::chrono::duration<double>(now - start).count();
        if (elapsed > DURATION + 1.0)
            break;
    }

    //Close UDP socket
    close(sockfd);

    //Print debug
    std::cout << "Captured samples: " << data.size()
              << " | Lost packets: " << lostPackets << "\n";

    //Return sample
    return data;
}

// =========================
// inverseSweep, due to: recorded_signal  *  inverse_sweep  =  impulse_response
// =========================
std::vector<double> inverseSweep(const std::vector<double>& s)
{
    // Number of samples in the sweep
    int N = s.size();

    // Allocate vector for inverse sweep
    std::vector<double> inv(N);

    //Same constant used in generateSweep
    double K = log(F2/F1);


    for (int n = 0; n < N; n++)
    {
        //Convert sample index to time
        double t = (double)n / SAMPLE_RATE;
        //Compute exponential weighting
        double w = exp(-t * K / DURATION);

        //The inverse sweep is the sweep played backwards in time, with the exponential weighting applied
        inv[n] = s[N-1-n] * w;
    }

    return inv;
}

// =========================
// Performs FFT‑based convolution of two signals
// =========================
std::vector<double> convolve(const std::vector<double>& x, const std::vector<double>& h)
{
    // Total output length = sum of input lengths
    int N = x.size() + h.size();

    // Allocate FFTW real valued input buffers
    double* in1 = (double*)fftw_malloc(sizeof(double)*N);
    double* in2 = (double*)fftw_malloc(sizeof(double)*N);

    // Allocate FFTW complex valued output buffers
    fftw_complex* X = (fftw_complex*)fftw_malloc(sizeof(fftw_complex)*(N/2+1));
    fftw_complex* H = (fftw_complex*)fftw_malloc(sizeof(fftw_complex)*(N/2+1));

    // Zero-pad both input signals to length N
    for (int i = 0; i < N; i++) {
        in1[i] = (i < (int)x.size()) ? x[i] : 0;
        in2[i] = (i < (int)h.size()) ? h[i] : 0;
    }

    //Create FFT plans for real to complex values
    auto p1 = fftw_plan_dft_r2c_1d(N, in1, X, FFTW_ESTIMATE);
    auto p2 = fftw_plan_dft_r2c_1d(N, in2, H, FFTW_ESTIMATE);

    //execute FFTs
    fftw_execute(p1);
    fftw_execute(p2);

    //Multiply spectra, Complex multiplication
    for (int i = 0; i < N/2+1; i++) {
        double re = X[i][0]*H[i][0] - X[i][1]*H[i][1];
        double im = X[i][0]*H[i][1] + X[i][1]*H[i][0];
        X[i][0] = re;
        X[i][1] = im;
    }

    //Create inverse FFT plan
    auto p3 = fftw_plan_dft_c2r_1d(N, X, in1, FFTW_ESTIMATE);
    //Execute inverse FFT
    fftw_execute(p3);

    //Normalize output by N
    std::vector<double> y(N);
    for (int i = 0; i < N; i++)
        y[i] = in1[i] / N;

    // Free FFTW buffers
    fftw_free(in1); fftw_free(in2);
    fftw_free(X); fftw_free(H);

    //Return convolution result
    return y;
}

// =========================
//  process (SINGLE WINDOW) + CALIBRATION
// =========================
void process(const std::vector<double>& impulse, const std::vector<double>& calFreq, const std::vector<double>& calCorr_dB)
{
    int peak = 0;
    double maxVal = 0;

    //Find peak value of the impulse response
    for (int i = 0; i < (int)impulse.size(); i++)
    {
        //Useing abeselute value to to the value being campable of being both posetive and negative
        if (fabs(impulse[i]) > maxVal)
        {
            maxVal = fabs(impulse[i]);
            peak = i; // store index of strongest sample
        }
    }



    //Define the window start posisiton
    int start = peak - SAMPLE_RATE * 0.05; //Start 50 ms before peak
    if (start < 0) start = 0;



    //Define window size    
    int winSize = SAMPLE_RATE * 0.3; //Window size: 300ms
    std::vector<double> win(winSize);



    //Extract the impulse response segment and apply Hann window
    for (int i = 0; i < winSize; i++)
    {
        int idx = start + i;

        //zero all values outside the window
        double val = (idx < (int)impulse.size()) ? impulse[idx] : 0.0;

        //Define Hann window
        double hann = 0.5 * (1 - cos(2*M_PI*i/(winSize-1)));

        //Apply window
        win[i] = val * hann;
    }



    //FFT the windowed impulse response
    int N = win.size();
    double* in = (double*)fftw_malloc(sizeof(double)*N);
    fftw_complex* out = (fftw_complex*)fftw_malloc(sizeof(fftw_complex)*(N/2+1));

    //copy windowed impulse response into FFT buffer
    for (int i = 0; i < N; i++)
        in[i] = win[i];

    //create FFT plan
    auto p = fftw_plan_dft_r2c_1d(N, in, out, FFTW_ESTIMATE);
    
    //Execute FFT
    fftw_execute(p);



    //Compute magnitude spectrum
    std::vector<double> mag(N/2+1);

    for (int i = 0; i < N/2+1; i++)
        mag[i] = sqrt(out[i][0]*out[i][0] + out[i][1]*out[i][1]) / N;

    //Free FFT buffers
    fftw_free(in);
    fftw_free(out);



    //Compute reference level, to normalize the response
    double ref = 0;
    int count = 0;

    for (int i = 0; i < (int)mag.size(); i++)
    {
        double freq = (double)i * SAMPLE_RATE / N;

        if (freq > 200 && freq < 2000)
        {
            ref += mag[i];
            count++;
        }
    }
    //Avoid division by zero
    ref = (count > 0) ? ref / count : 1.0;



    //Write the frequency response to file 
    std::ofstream file("freq_response.txt");

    for (int i = 0; i < (int)mag.size(); i++)
    {
        double freq = (double)i * SAMPLE_RATE / N;

        //STOP at 20 kHz
        if (freq > 20000)
            break;

        //Convert magnitude to dB
        double db = 20 * log10(mag[i] / ref + 1e-12);

        // Apply calibration in dB if available
        double corr_dB = 0.0;
        if (!calFreq.empty()) {
            corr_dB = interpLinear(calFreq, calCorr_dB, freq);
        }

        double db_cal = db + corr_dB;

        //Write line
        file << freq << " " << db_cal << " 0\n";
    }

    file.close();
}

// =========================
// main loop
// =========================
int main()
{
    //Toggle correction
    bool useCalibration = true;

    std::vector<double> calFreq, calCorr_dB;

    //Load or skip calibration
    if (useCalibration) {
        //Build calibration file from reference + test mic responses
        buildCalibrationFile("G.R.A.S Cal.txt", "used_mic.txt", "calibration.txt");
        // Load calibration curve into memory
        loadCalibration("calibration.txt", calFreq, calCorr_dB);
    } else {
        std::cout << "Calibration skipped\n";
    }

    //Generate exponential sweep
    auto sweep = generateSweep(6.0);

    //Start asynchronous audio capture thread, one thread for playback another for ESP32 recive
    std::vector<double> recorded;
    std::thread capThread([&]() { recorded = capture(); });

    //Send start to ESP32
    sendStart();
    
    //Play sweep
    playSweep(sweep);

    //Wait for capture to complete 
    capThread.join();

    //compute the inversesweep
    auto inv = inverseSweep(sweep);

    //Deconvolve recorded sweep, giving the impulseresponse
    auto impulse = convolve(recorded, inv);

    //Process impulse response
    process(impulse, calFreq, calCorr_dB);

    std::cout << "DONE\n";
}

